# Generated by Django 3.0.4 on 2020-03-24 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('year', models.DateField(verbose_name='release date')),
                ('genre', models.CharField(choices=[('FPS', 'First-person Shooter'), ('Action', 'Action'), ('Platformer', 'Platformer'), ('Adventure', 'Adventure'), ('RPG', 'Role-play Game'), ('Racing', 'Racing'), ('Puzzle', 'Puzzle'), ('Strategy', 'Strategy')], default='FPS', max_length=50)),
                ('esrb', models.CharField(choices=[('E', 'Everyone'), ('T', 'Teen'), ('M', 'Mature')], default='E', max_length=50)),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('games', models.ManyToManyField(to='main_app.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
